# Site settings
title: Robert Arbon 
description: >
 This is the personal website and blog of Robert Arbon, PhD candidate at the Unversity of Bristol. 

url: http://www.robert.arbon.com # the base hostname & protocol for your site

author:
  fullname: Robert Arbon 
  github: RobertArbon 
 #  disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
